name: Test
on:
  push:
    branches: [main, master]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'tests/**'
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -e '.[dev]'
      - run: pytest
